/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ComplainRouteImport } from './routes/complain'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplainRoute = ComplainRouteImport.update({
  id: '/complain',
  path: '/complain',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/complain': typeof ComplainRoute
  '/emergency': typeof EmergencyRoute
  '/quick': typeof QuickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/complain': typeof ComplainRoute
  '/emergency': typeof EmergencyRoute
  '/quick': typeof QuickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/complain': typeof ComplainRoute
  '/emergency': typeof EmergencyRoute
  '/quick': typeof QuickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/community' | '/complain' | '/emergency' | '/quick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/community' | '/complain' | '/emergency' | '/quick'
  id: '__root__' | '/' | '/community' | '/complain' | '/emergency' | '/quick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ComplainRoute: typeof ComplainRoute
  EmergencyRoute: typeof EmergencyRoute
  QuickRoute: typeof QuickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complain': {
      id: '/complain'
      path: '/complain'
      fullPath: '/complain'
      preLoaderRoute: typeof ComplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ComplainRoute: ComplainRoute,
  EmergencyRoute: EmergencyRoute,
  QuickRoute: QuickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
